DROP DATABASE IF EXISTS mss_db;
DROP USER IF EXISTS mss_admin;

CREATE USER mss_admin WITH PASSWORD '0';
CREATE DATABASE mss_db OWNER mss_admin;

\connect mss_db

SET ROLE mss_admin;

CREATE SCHEMA mss_transaction;
CREATE SCHEMA mss_analytics;

CREATE TABLE mss_transaction.users (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE mss_transaction.url (
    short_url VARCHAR(255) PRIMARY KEY,
    url       VARCHAR(2048) NOT NULL,
    user_id   INTEGER REFERENCES mss_transaction.users(id)
);

CREATE TABLE mss_analytics.raw (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url_id     VARCHAR(255) NOT NULL REFERENCES mss_transaction.url(short_url) ON DELETE CASCADE,
    hit_time   TIMESTAMP NOT NULL DEFAULT now(),
    ip_address VARCHAR(45)
);

CREATE INDEX idx_raw_url_hit ON mss_analytics.raw (url_id, hit_time);

RESET ROLE;